### ISSUE TITLE
PlayerChatEvent indicate "player" information in "message" object

### ISSUE THREAD

**Issue by tainalo2** [KK964/Minecraft_Websocket_Intergration#4]
**Describe the bug**
Event PlayerChatEvent is not returning the string in "message" object, but same player information than "player" object.

**To Reproduce**
1. Send this '"test pour voir" (test to see in french) in game chat'
2. See error : event is triggred to websocket client but without text message

**Expected behavior**
Expecting raw string message of the player in "message" object.

**Screenshots**
Raw message that my websocket client received : 

"Event PlayerChatEvent {"message":{"uuid":"b6b1a9d3-5165-4cea-8065-6b8267147c63","username":"tainalo2"},"player":{"uuid":"b6b1a9d3-5165-4cea-8065-6b8267147c63","username":"tainalo2"}}"

**Additional context**
Download and compilation with maven and java 11 on ubuntu system. At 12/03/2022
Thank you for your amazing work, i'm using it to dev twitch interaction over a nodered server.

**Comment by KK964** [comment]
This has been fixed in [this commit](https://github.com/KK964/Minecraft_Websocket_Intergration/tree/95bca8f27b1cb0e99c12b5ac0cf59c21725b59d3)

**Comment by tainalo2** [comment]
Thanks ! I have test and it's working.
